server:
  port: 9092
  servlet:
    context-path: /mongoTest

spring:
  application:
    name: mongoTest
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  data:
    mongodb:
      uri: mongodb://192.168.116.147:27018,192.168.116.147:27019,192.168.116.147:27320/teamis?replicaSet=haoyu

