server:
  port: 9092
  servlet:
    context-path: /mongo

spring:
  application:
    name: mongoTest
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  data:
    mongodb:
      uri: mongodb://localhost:27117,localhost:27217,localhost:27317/teamis?replicaSet=haoyuSet

